# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 777)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setText("")
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_Message = QtWidgets.QLabel(self.centralwidget)
        self.label_Message.setMinimumSize(QtCore.QSize(0, 20))
        self.label_Message.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_Message.setObjectName("label_Message")
        self.verticalLayout.addWidget(self.label_Message)
        self.msg = QtWidgets.QLabel(self.centralwidget)
        self.msg.setMinimumSize(QtCore.QSize(0, 200))
        self.msg.setMaximumSize(QtCore.QSize(16777215, 200))
        self.msg.setText("")
        self.msg.setObjectName("msg")
        self.verticalLayout.addWidget(self.msg)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_long_cam_shutter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_long_cam_shutter.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_long_cam_shutter.setObjectName("btn_long_cam_shutter")
        self.horizontalLayout_3.addWidget(self.btn_long_cam_shutter)
        self.btn_short_cam_shutter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_short_cam_shutter.setMaximumSize(QtCore.QSize(160, 16777215))
        self.btn_short_cam_shutter.setObjectName("btn_short_cam_shutter")
        self.horizontalLayout_3.addWidget(self.btn_short_cam_shutter)
        self.btn_capture = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capture.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_capture.setObjectName("btn_capture")
        self.horizontalLayout_3.addWidget(self.btn_capture)
        self.label_Tag = QtWidgets.QLabel(self.centralwidget)
        self.label_Tag.setObjectName("label_Tag")
        self.horizontalLayout_3.addWidget(self.label_Tag)
        self.plainTextEdit_Tag = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Tag.setMinimumSize(QtCore.QSize(0, 30))
        self.plainTextEdit_Tag.setMaximumSize(QtCore.QSize(800, 30))
        self.plainTextEdit_Tag.setObjectName("plainTextEdit_Tag")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_Tag)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_tag_calib_extrinsic = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tag_calib_extrinsic.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_tag_calib_extrinsic.setObjectName("btn_tag_calib_extrinsic")
        self.horizontalLayout_2.addWidget(self.btn_tag_calib_extrinsic)
        self.btn_tag_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tag_test.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_tag_test.setObjectName("btn_tag_test")
        self.horizontalLayout_2.addWidget(self.btn_tag_test)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_noise_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_noise_test.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_noise_test.setObjectName("btn_noise_test")
        self.horizontalLayout_4.addWidget(self.btn_noise_test, 0, QtCore.Qt.AlignLeft)
        self.btn_dark_current_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dark_current_test.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_dark_current_test.setObjectName("btn_dark_current_test")
        self.horizontalLayout_4.addWidget(self.btn_dark_current_test, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyImageCaptureTools"))
        self.label_Message.setText(_translate("MainWindow", "Message"))
        self.btn_long_cam_shutter.setText(_translate("MainWindow", "Long Camera Shutter"))
        self.btn_short_cam_shutter.setText(_translate("MainWindow", "Short Camera Shutter"))
        self.btn_capture.setText(_translate("MainWindow", "Capture"))
        self.label_Tag.setText(_translate("MainWindow", "Tag:"))
        self.btn_tag_calib_extrinsic.setText(_translate("MainWindow", "Tag=\'calib_extrinsic\'"))
        self.btn_tag_test.setText(_translate("MainWindow", "Tag=\'test\'"))
        self.btn_noise_test.setText(_translate("MainWindow", "noise test"))
        self.btn_dark_current_test.setText(_translate("MainWindow", "dark current test"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))

